[alembic]
script_location = alembic
sqlalchemy.url = sqlite:///./data/app.db

[loggers]
keys = root, sqlalchemy, alembic

[handlers]
keys = consoleHandler

[formatters]
keys = genericFormatter

[logger_root]
level = INFO
handlers = consoleHandler

[logger_sqlalchemy]
level = WARN
handlers = consoleHandler
qualname = sqlalchemy

[logger_alembic]
level = INFO
handlers = consoleHandler
qualname = alembic

[handler_consoleHandler]
class = StreamHandler
args = []
level = INFO
formatter = genericFormatter

[formatter_genericFormatter]
format = %(asctime)s - %(name)s - %(levelname)s - %(message)s
